github_api:
  host: https://api.github.com/
  login: mvs.vladislav@gmail.com
  password: 12345678
  client_id: client_id
  client_secret: client_secret
  repo_name: test-repo
  repo_description: Just a test repo
ssh:
  host: 192.168.56.101
  user: root
  password: 12345678
  key: /home/vladislav/.ssh/id_rsa
  passphrase: passphrase